### ISSUE TITLE
main.py FileNotFoundError

### ISSUE THREAD

**Issue by 0todd0000** [GuillaumeLam/PaCalC#1]
Attempting to run:

```
python main.py -v fast
```

yields a FileNotFoundError:

```
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/cycles_Normalized.pkl'
```

**Comment by 0todd0000** [comment]
From the main README page:

"Run code from repo [here](https://github.com/Vaibhavshahvr7/Surface-classification-Final)..."

```
Run code from repo [here](https://github.com/Vaibhavshahvr7/Surface-classification-Final)
```

Clicking on "here" returns a Page Not Found error, so it was unclear how to get started.

**Comment by GuillaumeLam** [comment]
Taken from the readme: 
```
Run code from repo [here](https://github.com/Vaibhavshahvr7/Surface-classification-Final) to generate the following file. Place the processed dataset from [here](https://drive.google.com/drive/folders/1XiyOS47Vvt_JM0cCqc-efDANtExbP9mG?usp=share_link) in the folder PaCalC/dataset.
```
The first link is the repo used to generate the file from the second link. So you can download the file from the second link and place it in the appropriate folder.

**Comment by 0todd0000** [comment]
Clicking on the first link yields a "Page Not Found" error.
How can I access the first link?

**Comment by GuillaumeLam** [comment]
It is likely because it is a private repo. The author of it Vaibhavshahvr7 will need to give you access to the repo Surface-classification-Final.

**Comment by GuillaumeLam** [comment]
I would highly recommend downloading the processed data from the google drive link (2nd link) to get the repo code running. Thank you for raising the issue, I'll update the readme shortly to reflect this difficulty.

**Comment by 0todd0000** [comment]
Understood. In that case I suggest removing the first link from the README file. If you provide just the link to the dataset it will be much clearer how to proceed.

Otherwise, if you'd like to reference the private repository, please do so after the dataset link, please add a warning clarifying that it may be a private repository, and please also add a brief explanation regarding how private repository access can be requested.
